name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

env:
  PERL_USE_UNSAFE_INC: 0
  AUTOMATED_TESTING: 1
  RELEASE_TESTING: 1

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    outputs:
      perl-versions: ${{ steps.perl-versions.outputs.perl-versions }}
    steps:
      - id: perl-versions
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: 5.8
          with-devel: false

  linux:
    needs: perl-versions
    runs-on: ubuntu-latest
    name: "linux ${{ matrix.perl-version }}"

    env:
      AUTHOR_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}
        include:
          - perl-version: "latest"
            run-extended-tests: true

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: "cpanfile"
      - run: perl Makefile.PL
      - run: make
      - run: make test
      - name: Extended Tests
        if: matrix.run-extended-tests
        run: prove -b xt/*.t

  macOS:
    needs: [linux]
    runs-on: macOS-latest

    env:
      AUTHOR_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v4
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: "cpanfile"
      - run: perl Makefile.PL
      - run: make
      - run: make test
      - name: Extended Tests
        run: prove -b xt/*.t

  windows:
    needs: [linux]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: "cpanfile"
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test
      - name: Extended Tests
        run: prove -b xt/*.t
